comment "Exported from Arsenal by Petrovic";

comment "Remove existing items";
removeAllWeapons player;
removeAllItems player;
removeAllAssignedItems player;
removeUniform player;
removeVest player;
removeBackpack player;
removeHeadgear player;
removeGoggles player;

comment "Add containers";
player forceAddUniform "TRYK_U_B_wh_blk_Rollup_CombatUniform";
player addItemToUniform "ACE_personalAidKit";
player addItemToUniform "ACE_surgicalKit";
for "_i" from 1 to 2 do {player addItemToUniform "ACE_morphine";};
for "_i" from 1 to 2 do {player addItemToUniform "ACE_atropine";};
for "_i" from 1 to 2 do {player addItemToUniform "ACE_epinephrine";};
for "_i" from 1 to 10 do {player addItemToUniform "ACE_quikclot";};
for "_i" from 1 to 2 do {player addItemToUniform "ACE_tourniquet";};
player addItemToUniform "ACE_Cellphone";
player addItemToUniform "ACE_Clacker";
player addItemToUniform "ACE_RangeTable_82mm";
for "_i" from 1 to 5 do {player addItemToUniform "ACE_key_lockpick";};
for "_i" from 1 to 2 do {player addItemToUniform "ACE_EarPlugs";};
for "_i" from 1 to 5 do {player addItemToUniform "ACE_CableTie";};
player addItemToUniform "ACE_ATragMX";
player addVest "TRYK_V_Bulletproof_BLK";
player addBackpack "B_FieldPack_blk";
for "_i" from 1 to 2 do {player addItemToBackpack "ACE_bodyBag";};
player addItemToBackpack "ACE_salineIV";
player addItemToBackpack "ACE_bloodIV";
player addItemToBackpack "ACE_plasmaIV";
player addItemToBackpack "ACE_Kestrel4500";
player addItemToBackpack "ACE_DefusalKit";
player addItemToBackpack "ACE_microDAGR";
player addItemToBackpack "ACE_MapTools";
player addItemToBackpack "MCC_multiTool";
for "_i" from 1 to 4 do {player addItemToBackpack "ACE_IR_Strobe_Item";};
for "_i" from 1 to 9 do {player addItemToBackpack "rhs_mag_9x19_17";};
for "_i" from 1 to 4 do {player addItemToBackpack "rhs_mag_m7a3_cs";};
for "_i" from 1 to 2 do {player addItemToBackpack "rhs_mag_an_m8hc";};
player addItemToBackpack "rhs_mag_m18_green";
player addItemToBackpack "rhs_mag_m18_red";
player addItemToBackpack "rhs_mag_m18_purple";
player addItemToBackpack "ACE_HandFlare_Green";
player addHeadgear "TRYK_H_headsetcap_blk";
player addGoggles "rhs_googles_black";

comment "Add weapons";
player addWeapon "rhs_weap_pya";
player addWeapon "Binocular";

comment "Add items";
player linkItem "ItemMap";
player linkItem "ItemCompass";
player linkItem "ItemWatch";
player additem "ACRE_PRC148";
player linkItem "ItemGPS";
