comment "Exported from Arsenal by Petrovic";

comment "Remove existing items";
removeAllWeapons player;
removeAllItems player;
removeAllAssignedItems player;
removeUniform player;
removeVest player;
removeBackpack player;
removeHeadgear player;
removeGoggles player;

comment "Add containers";
player forceAddUniform "TRYK_U_B_BLK";
player addItemToUniform "ACE_surgicalKit";
player addItemToUniform "ACE_personalAidKit";
for "_i" from 1 to 10 do {player addItemToUniform "ACE_quikclot";};
for "_i" from 1 to 3 do {player addItemToUniform "ACE_epinephrine";};
for "_i" from 1 to 2 do {player addItemToUniform "ACE_atropine";};
for "_i" from 1 to 4 do {player addItemToUniform "ACE_morphine";};
for "_i" from 1 to 2 do {player addItemToUniform "ACE_tourniquet";};
player addItemToUniform "ACE_Kestrel4500";
player addItemToUniform "ACE_Clacker";
for "_i" from 1 to 2 do {player addItemToUniform "ACE_EarPlugs";};
player addItemToUniform "ACE_DefusalKit";
player addVest "TRYK_V_ArmorVest_Delta";
for "_i" from 1 to 9 do {player addItemToVest "rhs_mag_30Rnd_556x45_M855A1_Stanag_No_Tracer";};
for "_i" from 1 to 5 do {player addItemToVest "rhs_mag_9x18_12_57N181S";};
for "_i" from 1 to 4 do {player addItemToVest "Chemlight_yellow";};
player addBackpack "TRYK_B_Coyotebackpack_BLK";
player addItemToBackpack "MCC_multiTool";
player addItemToBackpack "ACE_wirecutter";
player addItemToBackpack "ACE_MapTools";
player addItemToBackpack "ACE_microDAGR";
player addItemToBackpack "ACE_RangeTable_82mm";
player addItemToBackpack "ACE_SpareBarrel";
for "_i" from 1 to 5 do {player addItemToBackpack "ACE_key_lockpick";};
player addItemToBackpack "ACE_ATragMX";
for "_i" from 1 to 4 do {player addItemToBackpack "ACE_IR_Strobe_Item";};
for "_i" from 1 to 4 do {player addItemToBackpack "ACE_CableTie";};
player addItemToBackpack "ACE_Cellphone";
for "_i" from 1 to 2 do {player addItemToBackpack "ACE_bloodIV_250";};
for "_i" from 1 to 2 do {player addItemToBackpack "ACE_salineIV_250";};
for "_i" from 1 to 2 do {player addItemToBackpack "ACE_plasmaIV_250";};
for "_i" from 1 to 2 do {player addItemToBackpack "ACE_bodyBag";};
for "_i" from 1 to 4 do {player addItemToBackpack "rhs_mag_m67";};
for "_i" from 1 to 4 do {player addItemToBackpack "rhs_mag_mk3a2";};
for "_i" from 1 to 2 do {player addItemToBackpack "ACE_HandFlare_Red";};
for "_i" from 1 to 2 do {player addItemToBackpack "ACE_HandFlare_Green";};
for "_i" from 1 to 2 do {player addItemToBackpack "ACE_HandFlare_White";};
for "_i" from 1 to 3 do {player addItemToBackpack "rhs_mag_an_m8hc";};
for "_i" from 1 to 2 do {player addItemToBackpack "rhs_mag_m18_yellow";};
player addHeadgear "TRYK_H_PASGT_BLK";
player addGoggles "TRYK_kio_balaclava_ESS";

comment "Add weapons";
player addWeapon "rhs_weap_m4";
player addPrimaryWeaponItem "rhsusf_acc_SF3P556";
player addPrimaryWeaponItem "RH_SFM952V";
player addPrimaryWeaponItem "RH_compm4s";
player addPrimaryWeaponItem "rhsusf_acc_harris_bipod";
player addWeapon "rhs_weap_makarov_pmm";
player addWeapon "lerca_1200_black";

comment "Add items";
player linkItem "ItemMap";
player linkItem "ItemCompass";
player linkItem "ItemWatch";
player linkItem "tf_anprc148";
player linkItem "ItemGPS";
player linkItem "rhsusf_ANPVS_14";
